version: '3'
services:
  web:
    container_name: sample_api 
    image: node:latest
    ports:
      - "3000:3000"
    command: node /opt/api/app.js
    volumes:
      - ./volumes:/opt/api
    links:
      - db
      
  db:
    container_name: sample_api_db 
    image: mongo:latest 
    ports:
      - "27017"
